//CART
export const ADD_TO_CART = "CART/ADD_TO_CART";
export const DELETE_IN_CART = "CART/DELETE_IN_CART";
export const INCREASE_DISH_IN_CART = "CART/INCREASE_DISH_IN_CART";
export const DECREASE_DISH_IN_CART = "CART/DECREASE_DISH_IN_CART";

//DISHES
export const SET_DISHES = "DISHES/SET_DISHES";
export const REMOVE_ADMIN_DISH = "DISHES/REMOVE_ADMIN_DISH";

//CATEGORIES
export const SET_CATEGORIES = "CATEGORIES/SET_RESTAURANTS";

//CONTACTS
export const SET_CONTACTS = "CONTACTS/SET_CONTACTS";

//USER
export const SIGN_IN = "USER/SIGN_IN";
export const LOG_OUT = "USER/LOG_OUT";
export const SIGN_UP = "USER/SIGN_UP";
export const SIGN_IN_ERROR = "USER/SIGN_IN_ERROR";

//EVENT
export const SET_EVENTS = "EVENTS/SET_EVENTS";

//ORDERS
export const SET_ORDERS = "ORDERS/SET_ORDERS";

//CHECKOUT
export const SET_CHECKOUT = "CHECKOUT/SET_CHECKOUT";
export const CHECKOUT_ERROR = "CHECKOUT/CHECKOUT_ERROR";
